name: paseoconmiperro
favicon: null
layout_spectrum: 0.24805
typography_spectrum: 0.49415
title: 'Actividades para Perros en Colombia '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#74bfe7'
    - '#2a72ba'
    - '#02281d'
    - '#95670b'
  brandStrength: 1
  lightness: 0.29067180887795985
  saturation: 0.5135734155774117
  rhythmicContrast: 0.45545558095909655
purpose: []
