name: paseoconmiperro
favicon: null
layout_spectrum: 0.75461
typography_spectrum: 0.49415
title: 'Actividades para Perros en Colombia '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030657'
    - '#043bef'
    - '#37b6fd'
    - '#043700'
    - '#5cb72a'
  brandStrength: 1
  lightness: 0.29067180887795985
  saturation: 0.5135734155774117
  rhythmicContrast: 0.45545558095909655
purpose: []
