name: paseoconmiperro
favicon: null
layout_spectrum: 0.2897867155261338
typography_spectrum: 0.38520668214187026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7101390594616532
  lightness: 0.29067180887795985
  saturation: 0.5135734155774117
  rhythmicContrast: 0.45545558095909655
purpose: []
