name: De paseo con mi perro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49415
title: 'Actividades para Perros en Colombia '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#86c5bc'
    - '#010101'
    - '#493628'
    - '#f8b020'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
